"""changes to user model for profile pic

Revision ID: 12cf69dd4268
Revises: cdbd6d193b9e
Create Date: 2021-03-18 02:29:41.134971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cf69dd4268'
down_revision = 'cdbd6d193b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePhotoUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePhotoUrl')
    # ### end Alembic commands ###
